# The Site Configuration

theme: jekyll-theme-chirpy

lang: en

timezone:

title: 𝐎𝐗𝐇𝐋𝟑𝐏 [RE]

tagline: Reversing Engineering & Web Exploitation

description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

url: "https://sh4lps.github.io"

github:
  username: Sh4lps

twitter:
  username: Sh4lps

social:
  name: Sh4lps
  email:
  links:
    - https://x.com/Sh4lps
    - https://github.com/Sh4lps

avatar: "https://i.pinimg.com/736x/b2/e9/e2/b2e9e263a9ad57787807180b35f0be9b.jpg"

toc: true

comments:
  provider:

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
